adv-interval: 3
average-factor: 50
batch-size: 8
blindspot-rate: 0.05
cnn-base-channel: 8
dataset: datasets/PA_2081b
gan-lambda: 5
gpu: true
image-channel: 1
image-extension: tif
iter-per-epoch: 200
iterations: 200000
learning-rate: 0.0001
load-weights: supervised2022-08-07_13-02-52
loss-gain: 1000
norm-range:
- 4420
- 48017
norm-range-target:
- 6265
- 38567
only-pixel-loss: false
percep-lambda: 0.5
resolution: 512
test-interval: 5
threads: 32
up-scale-factor: 2
